ARG MUSL_TARGET=x86_64-linux-musl
FROM musl-cross-make-$MUSL_TARGET
ARG MUSL_TARGET

RUN cd /build && \
wget -O source.tar.gz https://zlib.net/zlib-1.2.11.tar.gz && \
tar xf source.tar.gz

RUN export PATH=/build/cross/bin:$PATH && \
cd /build/zlib-* && \
CC="$MUSL_TARGET-gcc" \
CFLAGS="-static -frandom-seed=pulse" \
./configure \
--prefix=/output \
--static && \
make -j$(nproc) && \
make install

CMD bash
