ARG MUSL_TARGET=x86_64-linux-musl
FROM musl-cross-make-$MUSL_TARGET
ARG MUSL_TARGET

WORKDIR /build
RUN download https://mirrors.edge.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v1.46.5/e2fsprogs-1.46.5.tar.gz source.tar.gz 0786fadd77421e04b21f3a79513c5d8d9232f82eb8bea68f3af46f2d98bdd889 && tar xf source.tar.gz
RUN export PATH=/build/cross/bin:$PATH && \
cd e2fsprogs-* && \
mkdir build && \
cd build && \
export CC="$MUSL_TARGET-gcc" && \
export CFLAGS="-static -frandom-seed=pulse" && \
export LDFLAGS=--static && \
../configure \
--host=$($MUSL_TARGET-gcc -dumpmachine) \
--prefix=/output && \
make -j$(nproc) && \
make install

CMD bash
