ARG MUSL_TARGET=x86_64-linux-musl
FROM musl-cross-make-${MUSL_TARGET}
ARG MUSL_TARGET


WORKDIR /build
RUN download https://github.com/libfuse/libfuse/releases/download/fuse-2.9.9/fuse-2.9.9.tar.gz source.tar.gz d0e69d5d608cc22ff4843791ad097f554dd32540ddc9bed7638cc6fea7c1b4b5 && tar xf source.tar.gz
RUN export PATH=/build/cross/bin:$PATH && \
cd fuse-* && \
CC="$MUSL_TARGET-gcc" \
CFLAGS="-static -frandom-seed=pulse -I/output/include" \
LDFLAGS="-L/output/lib" \
./configure \
--prefix=/output \
--host=$($MUSL_TARGET-gcc -dumpmachine) && \
make -j$(nproc) && \
make install

CMD bash
