ARG MUSL_TARGET=x86_64-linux-musl
FROM musl-cross-make-${MUSL_TARGET}
ARG MUSL_TARGET

RUN cd /build && \
wget -O source.tar.bz2 https://busybox.net/downloads/busybox-1.33.1.tar.bz2 && \
tar xf source.tar.bz2

RUN export PATH=/build/cross/bin:$PATH && \
mkdir -p /output/bin && \
cd /build/busybox-* && \
export CFLAGS="-frandom-seed=pulse -I/output/include" && \
export LDFLAGS="--static -L/output/lib" && \
make defconfig && \
make CROSS_COMPILE="$MUSL_TARGET-" -j$(nproc) && \
$MUSL_TARGET-strip busybox && \
cp busybox /output/bin/busybox

CMD bash
