ARG MUSL_TARGET=x86_64-linux-musl
FROM musl-cross-make-$MUSL_TARGET
ARG MUSL_TARGET

WORKDIR /build
RUN download https://invisible-mirror.net/archives/ncurses/ncurses-6.2.tar.gz source.tar.gz 30306e0c76e0f9f1f0de987cf1c82a5c21e1ce6568b9227f7da5b71cbea86c9d && tar xf source.tar.gz
RUN export PATH=/build/cross/bin:$PATH && \
cd ncurses-* && \
CC="$MUSL_TARGET-gcc" \
./configure \
--prefix=/output \
--host=$($MUSL_TARGET-gcc -dumpmachine) \
--disable-stripping \
--enable-static \
--with-normal \ 
--disable-shared && \
make -j$(nproc) && \
make install

CMD bash
