ARG MUSL_TARGET=x86_64-linux-musl
FROM musl-cross-make-$MUSL_TARGET
ARG MUSL_TARGET

RUN cd /build && \
wget -O source.tar.gz https://www.tcpdump.org/release/libpcap-1.10.1.tar.gz && \
tar xf source.tar.gz

RUN export PATH=/build/cross/bin:$PATH && \
cd /build/libpcap-* && \
CC="$MUSL_TARGET-gcc" \
CFLAGS="-static -frandom-seed=pulse" \
./configure \ 
--prefix=/output \
--host=$($MUSL_TARGET-gcc -dumpmachine) \
--with-pcap=linux && \
make -j$(nproc) && \
make install

CMD bash
