ARG MUSL_TARGET=x86_64-linux-musl
FROM musl-cross-make-$MUSL_TARGET
ARG MUSL_TARGET

WORKDIR /build
RUN download https://ftp.gnu.org/pub/gnu/gettext/gettext-0.21.tar.gz source.tar.gz c77d0da3102aec9c07f43671e60611ebff89a996ef159497ce8e59d075786b12 && tar xf source.tar.gz
RUN export PATH=/build/cross/bin:$PATH && \
cd gettext-* && \
export CC="$MUSL_TARGET-gcc" && \
export CFLAGS="-static -frandom-seed=pulse" && \
./configure \
--host=$($MUSL_TARGET-gcc -dumpmachine) \
--prefix=/output && \
make -j$(nproc) && \
make install

CMD bash
