ARG MUSL_TARGET=x86_64-linux-musl
FROM musl-cross-make-$MUSL_TARGET
ARG MUSL_TARGET

RUN cd /build && \
wget -O source.tar.gz https://ftp.pcre.org/pub/pcre/pcre-8.45.tar.gz && \
tar xf source.tar.gz

RUN export PATH=/build/cross/bin:$PATH && \
cd /build/pcre-* && \
CC="$MUSL_TARGET-gcc" \
CFLAGS="-fPIC -static -frandom-seed=pulse" \
./configure \
--host=$($MUSL_TARGET-gcc -dumpmachine) \
--prefix=/output && \
make -j$(nproc) && \
make install

CMD bash
