ARG MUSL_TARGET=x86_64-linux-musl
FROM ncurses-6.2-${MUSL_TARGET} AS ncurses
FROM musl-cross-make-$MUSL_TARGET
ARG MUSL_TARGET

COPY --from=ncurses /output /output

WORKDIR /build
RUN download https://mirror.fsmg.org.nz/gnu/readline/readline-8.1.tar.gz source.tar.gz f8ceb4ee131e3232226a17f51b164afc46cd0b9e6cef344be87c65962cb82b02 && tar xf source.tar.gz
RUN export PATH=/build/cross/bin:$PATH && \
cd readline-* && \
CC="$MUSL_TARGET-gcc" \
./configure \
--prefix=/output \
--with-curses \
--host=$($MUSL_TARGET-gcc -dumpmachine) \
--enable-static \
--disable-shared && \
make -j$(nproc) && \
make install

CMD bash
