ARG MUSL_TARGET=x86_64-linux-musl
FROM musl-cross-make-$MUSL_TARGET
ARG MUSL_TARGET

WORKDIR /build
RUN download https://www.tcpdump.org/release/libpcap-1.10.1.tar.gz source.tar.gz ed285f4accaf05344f90975757b3dbfe772ba41d1c401c2648b7fa45b711bdd4 && tar xf source.tar.gz
RUN export PATH=/build/cross/bin:$PATH && \
cd libpcap-* && \
CC="$MUSL_TARGET-gcc" \
CFLAGS="-static -frandom-seed=pulse" \
./configure \ 
--prefix=/output \
--host=$($MUSL_TARGET-gcc -dumpmachine) \
--with-pcap=linux && \
make -j$(nproc) && \
make install

CMD bash
