ARG MUSL_TARGET=x86_64-linux-musl
FROM musl-cross-make-$MUSL_TARGET
ARG MUSL_TARGET

RUN cd /build && \
wget -O source.tar.gz ftp://xmlsoft.org/libxml2/libxml2-2.9.12.tar.gz && \
tar xf source.tar.gz

RUN export PATH=/build/cross/bin:$PATH && \
cd /build/libxml2-* && \
CC="$MUSL_TARGET-gcc" \
CFLAGS="-static -frandom-seed=pulse" \
./configure \
--host=$($MUSL_TARGET-gcc -dumpmachine) \
--prefix=/output && \
make -j$(nproc) && \
make install

CMD bash
