ARG MUSL_TARGET=x86_64-linux-musl
FROM musl-cross-make-$MUSL_TARGET
ARG MUSL_TARGET

WORKDIR /build
RUN download https://github.com/protocolbuffers/protobuf/releases/download/v21.1/protobuf-cpp-3.21.1.tar.gz source.tar.gz 9ccabf07bd087bca3bb37067e04bf1d7377f0d60311cf3d2aa88e7af4c49a177 && tar xf source.tar.gz
RUN export PATH=/build/cross/bin:$PATH && \
cd protobuf-* && \
export CC="$MUSL_TARGET-gcc" && \
export CXX="$MUSL_TARGET-g++" && \
export CFLAGS="-static -frandom-seed=pulse" && \
./configure \
--disable-shared \
--enable-static \
--host=$($MUSL_TARGET-gcc -dumpmachine) \
--prefix=/output && \
make -j$(nproc) && \
make install

CMD bash
