#!/usr/bin/python3 -u

"""
Download a file from a URL and validate the SHA256 checksum while downloading.

Michael Fincham <michael@hotplate.co.nz> 2021-08-20
"""

import sys
import os
import argparse
import hashlib
import urllib.request
import tempfile

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "url", help="URL to download from"
    )
    parser.add_argument(
        "destination",
        help="destination file"
    )
    parser.add_argument(
        "sha256sum",
        help="SHA256 checksum to match again"
    )
    args = parser.parse_args()

    block_size = 1024 * 1024
    checksum = hashlib.sha256()
    response = urllib.request.urlopen(args.url)
    return_code = 0
    sha256sum = args.sha256sum.lower()
    print("Downloading '%s'..." % args.url)
    with tempfile.NamedTemporaryFile() as f:
        while True:
            block = response.read(block_size)
            if not block:
                break
            f.write(block)
            checksum.update(block)
            print(".", end="")
        print("")
        if checksum.hexdigest() == sha256sum:
            os.link(f.name, args.destination)
        else:
            sys.stderr.write("error: checksum didn't match for '%s', not saving file. got %s and expected %s.\n" % (args.url, checksum.hexdigest(), sha256sum))
            return_code = 1
    sys.exit(return_code)
